### ISSUE TITLE
Ability to include name of property for autofixture generation

### ISSUE THREAD

**Issue by distantcam** [progala2/Buildenator#46]
I'm trying to integrate Buildenator + AutoBogus into a project, and I've hit an issue.

Currently when generating the properties I can only see the type of the property by overriding the `additionalConfiguration` string and using `{0}` for the type.

It would be useful if the name of the property was also included in this template (with `{1}` for example) so as to provide extra customisation depending on the property name.

Thanks

**Comment by progala2** [comment]
I will take a look into that this week, thanks for the proposition!

**Comment by progala2** [comment]
the `additionalConfiguration ` is used for an additional configuration of your **fixture instance.** not for properties initialization.

I guess you're talking about the `createSingleFormat`, because in `additionalConfiguration ` there is a type and an instance name provided. You can check out example here: `AutoFixtureWithMoqConfigurationAttribute`.

#48
